Wed 29 Nov 2017 14:34:47 API.py [line:660] INFO start
Wed 29 Nov 2017 14:34:47 API.py [line:692] INFO thread 0 start.
Wed 29 Nov 2017 14:34:47 API.py [line:695] INFO thread 0's token_index 49
Wed 29 Nov 2017 14:34:47 API.py [line:696] INFO {u'access_token': u'4811953092-IbtWCXXjDBml4kquhZPnCFNxBNcSR0Bm7tX3mLP', u'consumer_secret': u'LivsS9DTKh4Xmfo2vOG2tpKmrj8lxsYqiDgZLamPBJahFqnjUo', u'consumer_key': u'fO4lXV6LLz5e1Ew6uRDtvXpIQ', u'access_token_secret': u'O2aJFmkL7iuX3Sytzg521qLcZZDv97UR0WVYH724bmlHH'}
Wed 29 Nov 2017 14:34:47 API.py [line:697] INFO [u'kill']
Wed 29 Nov 2017 14:34:47 API.py [line:698] INFO ['192.168.1.148:8118']
Wed 29 Nov 2017 14:34:57 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:34:57 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:02 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:02 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:09 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:09 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:14 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:14 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:19 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:19 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:32 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:32 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:38 TwitterError.py [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
Wed 29 Nov 2017 14:35:38 API.py [line:222] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error('Invalid response from tunnel request',)))
