Tue 28 Nov 2017 11:29:26 TwitterError __init__ 5752 Thread-4 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Tue 28 Nov 2017 11:29:26 rest_api get_users_lookup 5752 Thread-4 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
